### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by zgd716** [laulampaul/WDNet_demoire#1]
大佬，数据集可否放到百度网盘或者阿里云盘，多谢

**Comment by laulampaul** [comment]
> 大佬，数据集可否放到百度网盘或者阿里云盘，多谢

链接：https://pan.baidu.com/s/1f4uhpYMv6eNVbhxrhRp_QA 
提取码：3b0x
but downloading using baidu drive is slow, I think you 'd better download with the original link
